# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: crvsf/coeff-flow

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script: 
  #    - apt update && apt-get install -y make autoconf cmake clang libboost-all-dev wget g++
    
  script: 
    - cd /coeff-flow && git pull # update code
    - cd /coeff/flow/build && cmake .. && make # remake if it needs to be remade
    
  #artifacts:
  #  paths:
  #    - mybinary
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
test:
  stage: test
  script:
    - echo success
